name: Integration test
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    container: cloudfoundry/cf-deployment-concourse-tasks:latest
    steps:
      - uses: actions/checkout@v2
      - env:
          TOOLSMITH_TOKEN: ${{ secrets.TOOLSMITH_TOKEN }}
        run: |
          while ! curl -X POST "https://environments.toolsmiths.cf-app.com/pooled_gcp_engineering_environments/claim?api_token=${TOOLSMITH_TOKEN}&pool_name=cf-deployment&notes=github-actions-syslog-release" > metadata.json
          do
              exit 1
              sleep 1
          done

          eval "$(bbl print-env --metadata-file ./metadata)"
          ./scripts/test
      - if: always()
        env:
          TOOLSMITH_TOKEN: ${{ secrets.TOOLSMITH_TOKEN }}
        run: |
          curl -X POST "https://environments.toolsmiths.cf-app.com/pooled_gcp_engineering_environments/unclaim?api_token=${TOOLSMITH_TOKEN}&name=$(cat metadata.json | jq -r .name)"

