name: Integration Test
on:
  pull_request:
    branches:
    - main
jobs:
  integration-test:
    runs-on: ubuntu-latest
    container: cloudfoundry/cf-deployment-concourse-tasks:latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Claim environment
        env:
          TOOLSMITH_TOKEN: ${{ secrets.TOOLSMITH_TOKEN }}
        run: |
          if ! curl --fail -X POST "https://environments.toolsmiths.cf-app.com/pooled_gcp_engineering_environments/claim?api_token=${TOOLSMITH_TOKEN}&pool_name=cf-deployment&notes=github-actions-syslog-release" > metadata.json
          then
              echo "UNABLE TO CLAIM AN ENVIRONMENT, PLEASE RETRY LATER"
              exit 1
          fi
          eval "$(bbl print-env --metadata-file ./metadata.json)"
      - run: ./scripts/test
      - name: Unclaim environment
        if: always()
        env:
          TOOLSMITH_TOKEN: ${{ secrets.TOOLSMITH_TOKEN }}
        run: |
          curl -X POST "https://environments.toolsmiths.cf-app.com/pooled_gcp_engineering_environments/unclaim?api_token=${TOOLSMITH_TOKEN}&name=$(cat metadata.json | jq -r .name)"

